### ISSUE TITLE
Input contains NaN, infinity or a value too large for dtype('float32') when using dispersion_method ='UMAP'

### ISSUE THREAD

**Issue by Moldoteck** [damithsenanayake/SONG#2]
The error occurs at this line
 output = disp_model.fit_transform(X_pc)

**Comment by damithsenanayake** [comment]
Hi Modoteck  could you provide us the code you used this with?

**Comment by Moldoteck** [comment]
I have created an instance with SONGInstance = SONG(n_components=2,n_neighbors=15,random_seed=42, dispersion_model='UMAP') . After this i have created an embedding with fit for  about 100k samples with 64 dims each dataset. When i do transform for new data, one sample of 64 dims, it gives me that error. If i use just SONGInstance = SONG(n_components=2,n_neighbors=15,random_seed=42), then everything works ok. So the problem is certainly in part related to PCA/UMAP. 

These are the warnings>

```
C:\ProgramData\Anaconda3\envs\dev_38_tf22\lib\site-packages\song\song.py:308: RuntimeWarning: invalid value encountered in true_divide
  Y_init = 10 * (Y - Y.min(axis=0)) / (Y.max(axis=0) - Y.min(axis=0))
C:\ProgramData\Anaconda3\envs\dev_38_tf22\lib\site-packages\sklearn\decomposition\_pca.py:461: RuntimeWarning: invalid value encountered in true_divide
  explained_variance_ = (S ** 2) / (n_samples - 1)
```

And this is the traceback:

```
Traceback (most recent call last):
  ................................................................................
  File "C:\ProgramData\Anaconda3\envs\dev_38_tf22\lib\site-packages\song\song.py", line 314, in transform
    output = disp_model.fit_transform(X_pc)
  File "C:\ProgramData\Anaconda3\envs\dev_38_tf22\lib\site-packages\umap\umap_.py", line 2014, in fit_transform
    self.fit(X, y)
  File "C:\ProgramData\Anaconda3\envs\dev_38_tf22\lib\site-packages\umap\umap_.py", line 1624, in fit
    init = check_array(self.init, dtype=np.float32, accept_sparse=False)
  File "C:\ProgramData\Anaconda3\envs\dev_38_tf22\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "C:\ProgramData\Anaconda3\envs\dev_38_tf22\lib\site-packages\sklearn\utils\validation.py", line 644, in check_array
    _assert_all_finite(array,
  File "C:\ProgramData\Anaconda3\envs\dev_38_tf22\lib\site-packages\sklearn\utils\validation.py", line 96, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
```

**Comment by damithsenanayake** [comment]
> I have created an instance with SONGInstance = SONG(n_components=2,n_neighbors=15,random_seed=42, dispersion_model='UMAP') . After this i have created an embedding with fit for about 100k samples with 64 dims each dataset. When i do transform for new data, one sample of 64 dims, it gives me that error. If i use just SONGInstance = SONG(n_components=2,n_neighbors=15,random_seed=42), then everything works ok. So the problem is certainly in part related to PCA/UMAP.
> 
> These are the warnings>
> 
> ```
> C:\ProgramData\Anaconda3\envs\dev_38_tf22\lib\site-packages\song\song.py:308: RuntimeWarning: invalid value encountered in true_divide
>   Y_init = 10 * (Y - Y.min(axis=0)) / (Y.max(axis=0) - Y.min(axis=0))
> C:\ProgramData\Anaconda3\envs\dev_38_tf22\lib\site-packages\sklearn\decomposition\_pca.py:461: RuntimeWarning: invalid value encountered in true_divide
>   explained_variance_ = (S ** 2) / (n_samples - 1)
> ```
> 
> And this is the traceback:
> 
> ```
> Traceback (most recent call last):
>   ................................................................................
>   File "C:\ProgramData\Anaconda3\envs\dev_38_tf22\lib\site-packages\song\song.py", line 314, in transform
>     output = disp_model.fit_transform(X_pc)
>   File "C:\ProgramData\Anaconda3\envs\dev_38_tf22\lib\site-packages\umap\umap_.py", line 2014, in fit_transform
>     self.fit(X, y)
>   File "C:\ProgramData\Anaconda3\envs\dev_38_tf22\lib\site-packages\umap\umap_.py", line 1624, in fit
>     init = check_array(self.init, dtype=np.float32, accept_sparse=False)
>   File "C:\ProgramData\Anaconda3\envs\dev_38_tf22\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
>     return f(**kwargs)
>   File "C:\ProgramData\Anaconda3\envs\dev_38_tf22\lib\site-packages\sklearn\utils\validation.py", line 644, in check_array
>     _assert_all_finite(array,
>   File "C:\ProgramData\Anaconda3\envs\dev_38_tf22\lib\site-packages\sklearn\utils\validation.py", line 96, in _assert_all_finite
>     raise ValueError(
> ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
> ```

Hi I'm sorry for the delay. May I please confirm that you tried to transform a single vector from the subsequent input?

**Comment by Moldoteck** [comment]
Hi. Yes. I want to transform just one vector there

**Comment by damithsenanayake** [comment]
I see. SONG cannot transform only one instance with the UMAP distortion, but I have now tried to resolve this commit 34cf8556f220b34f8f383852947bf16bd443703d and also see version 1.2.0.10. 

However my advice is to try and provide at least two inputs together to the transform function. Otherwise the scale calculation as you have pointed out results in a zero division (since Y.max(axis=0) = Y.min(axis=0)). This zero division then creates a situation which messes up the whole thing.

**Comment by damithsenanayake** [comment]
If it works for you , let me know so that we can close this issue. :)

**Comment by Moldoteck** [comment]
> 
> 
> If it works for you , let me know so that we can close this issue. :)

Yes, now it seems to work. Can you elaborate a bit what have you changed?

**Comment by damithsenanayake** [comment]
Hi Moltodeck, sorry again for the delayed response. The logic here is that I use the SONG visualizations as an initialization for the UMAP 'dispersion' that we do. With that in mind, we're basically fitting a simpler UMAP model (lower no. of iterations, smaller learning rates etc.), and UMAP inherently can't project a single data point as it requires the relative position of at least two others to properly place a point in a two-dimensional representation. I have therefore used a pre-trained UMAP instead of training one anew in the case you're predicting a single point. 

I again however strongly advise against using this approach to project a single datapoint, but rather wait for at least three datapoints to gather (in the case of streaming data) or project a small batch and visualize the one you want.
